name = "ai-background-remover"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[[d1_databases]]
binding = "DB"
database_name = "ai-background-remover-db"
database_id = "643d2e7e-79e2-44c1-ad6e-5d41933e12e2"
